version: 2

models:
  - name: order_details
    description: This table has information about user's first order that was
                 not cancelled

    columns:
      - name: order_id
        description: This is a unique identifier for an order
        tests:
          - unique
          - not_null

      - name: user_id
        description: This is a unique identifier for a user
        tests:
          - not_null

      - name: created_at
        description: The timestamp value for when the order was created
        tests:
          - not_null

      - name: updated_at
        description: The timestamp value for when the order was updated

      - name: updated_at
        description: The timestamp value for when the order was shipped

      - name: currency
        description: The currency in which the payment was made

      - name: order_status
        description: The status flag of the order
        tests:
          - not_null

      - name: order_status_category
        description: The status category flag of the order
        tests:
          - not_null

      - name: country_type
        description: This flag determines if the order is to be shipped within
                     the US or internationl

      - name: shipping_method
        description: The shipping method used for the order

      - name: purchase_device_type
        description: Purchase device information through which the order was
                     placed further classified into categories

      - name: purchase_device
        description: Purchase device information through which the order was
                     placed

      - name: first_order_id
        description: User's first order_id

      - name: amount_total_cents
        description: Total amount of the order in cents

      - name: gross_tax_amount_cents
        description: Gross tax amount of the order in cents

      - name: gross_amount_cents
        description: Gross amount of the order in cents

      - name: gross_shipping_amount_cents
        description: Gross shipping amount of the order in cents

      - name: gross_total_amount_cents
        description: Gross total amount of the order in cents combining tax
                     amount, gross order amount and shipping amount

      - name: user_type
        description: This field flags if the order was from a new user or
                     returning user
        tests:
          - not_null

      - name: total_amount_cents
        description: Total amount of the order in cents

      - name: order_amount_total
        description: Total amount of the order in $

      - name: total_amount
        description: Total amount of the order in $

      - name: gross_tax_amount
        description: Gross tax amount of the order in $

      - name: gross_amount
        description: Gross amount of the order in $

      - name: gross_shipping_amount
        description: Gross shipping amount of the order in $

      - name: gross_total_amount
        description: Gross total amount of the order in $ combining tax
                     amount, gross order amount and shipping amount
